### ISSUE TITLE
Difference between this module and node-wkhtmltopdf?

### ISSUE THREAD

**Issue by nwhitmont** [tcort/wkhtmltox#12]
Hi, I'm wondering what the difference is between this module and https://www.npmjs.com/package/wkhtmltopdf ?

Is there some additional feature that you wanted to add or something about `node-wkhtmltopdf` that wasn't working for you?

**Comment by tcort** [comment]
That module spawns a new instance of the `wkhtmltopdf` binary for each conversion. This module, `wkhtmltox`, has several instances of the program ready and waiting for input. This provides better performance for long running services that occasionally render PDFs because the 50MB+ `wkhtmltopdf` binary doesn't need to be loaded for each render. In the past, when I was developing `wkhtmltox`, it was several seconds faster per render than the other module; I haven't done a comparison lately.

Additionally, `wkhtmltox` provides an interface for converting HTML to a `png` or `jpg`. I don't think the other module does that.

**Comment by nwhitmont** [comment]
awesome. thanks for the context @tcort !
